Isolation of snap and service code within ovn
canonical/microovn pull request #155
Opened 2024-07-30 14:31 UTC by crypticC0der

This removes certain parts of the ovn package codebase for controlling services and interacting with snap, and moves them to their own package. This was needed as the ovn package was seemingly getting bloated and this strips it down a bit

2024-07-30 16:04 UTC, fnordahl reviewed
Hey, MJ, thanks for the patch!

This change appears to move two modules, `snap` and `services`. I think that calls for two separate commits as well to contain the two logical units of change?

The reason why this is important is that you never know what the future holds, perhaps we want to cherry pick one of the changes to a stable branch, or revert one of the changes, or maybe just have a clear explanation for why something was changed on `git blame`.

2024-07-30 17:33 UTC, mkalcok commented
> I think that calls for two separate commits as well to contain the two logical units of change?

@fnordahl does it apply even when the changes are depending on each other? Because without moving snap-related functions to the `snap` package, contents of the `services` would have to remain in the `ovn` package.

Though I didn't do a full review yet, I have few notes:

Is it necessary to rename `node` package to `services`? I thought that the original package name was rather semantically fitting. It had functions like `HasService` which naturally translated to calls like `node.HasService()`, answering question "Does this node has this service". Even with your additions of `DisableService` and `EnableService`, calls like `node.EnableService()` (enable service on this node) would make a lot of sense.
Current implementation feels bit stuttery `services.HasService()`.

Now that the `snap` package is isolated, functions in this package could lose the `snap` prefix, otherwise it again leads to a lot of stuttering with calls like `snap.snapStart()`.

2024-07-30 18:12 UTC, fnordahl commented
> @fnordahl does it apply even when the changes are depending on each other? Because without moving snap-related functions to the `snap` package, contents of the `services` would have to remain in the `ovn` package.

While I have not dived into the the details, I see one group of files changed referring to only one of the modules and another referring to the other module, so presumably those changes can be made in separate commits?

2024-07-31 11:39 UTC, crypticC0der commented
wow these commits are now in two!!!!!

2024-07-31 11:53 UTC, crypticC0der commented
> Now that the snap package is isolated, functions in this package could lose the snap prefix, otherwise it again leads to a lot of stuttering with calls like snap.snapStart().
I entirely agree on this

> Is it necessary to rename node package to services?
I dont think so, but I think that the service related functionality should be in the same place, so either in node or service

2024-08-01 10:49 UTC, crypticC0der commented
I have made a commit changing the snap commands to 
snap.Snap* to just snap.*

2024-08-02 07:34 UTC, mkalcok commented
> I dont think so, but I think that the service related functionality should be in the same place, so either in node or service

I agree with pulling of the `{Enable,Disable}Service` functions out of the `ovn` package, but if we are going to rename existing packages, there needs to be a good reason for it.

2024-08-02 12:28 UTC, crypticC0der commented
@mkalcok should be all good now

2024-08-05 07:32 UTC, mkalcok requested changes
Overall looks good, thank you. I have but one last request, since we will be enabling linter that ensures GoDocs, could you please add them for functions/structures that you recently added (and moved in this change)?
* SrvName
* CheckValidService
* DisableService
* EnableService

2024-08-05 07:32 UTC, mkalcok commented on microovn/snap/snap.go
> +func Stop(service string, disable bool) error {
GoDoc does not match the renamed function

2024-08-05 07:32 UTC, mkalcok commented on microovn/node/node.go
Name of the file doesn't matter that much, since the package name remains `node`, though I'm still wondering if the file name change was necessary. Previous logic behind naming was that this package holds functions related to specific MicroOVN node and the file `services` would sub-group functions for services on the specific node.

2024-08-05 10:01 UTC, mkalcok approved these changes
Thank you, LGTM.

2024-08-05 10:11 UTC, merged