Remove 'microovn.' prefix in OVN commands
canonical/microovn pull request #207
Opened 2024-11-25 14:19 UTC by crypticC0der

Automatic aliases have been enabled in the MicroOVN snap [1], so documentation has been updated to drop this prefix and rewrite certain small sections talking about how to run OVN commands through MicroOVN.

[1]: https://forum.snapcraft.io/t/alias-request-for-various-microovn-binaries/43755/5

2024-11-25 15:30 UTC, mkalcok requested changes
Overall LGTM, thanks for the update. However I think that we would also benefit from either a reference or an explanation of the aliasing system, stating that OVN/OVS binaries can be executed either via `microovn.` prefixed commands or directly thanks to automatically created aliases (that can be inspected via `snap aliases`).
Also, since these auto aliases are not related to the microovn snap version, but rather they are something managed by the snap store, it would be good to find out if (when?) existing installations gain access to these aliases, and document that as well. Otherwise just dropping the prefixes in the documentation can lead to a confusion of users of existing installations.

2024-12-03 10:23 UTC, fnordahl commented
> Overall LGTM, thanks for the update. However I think that we would also benefit from either a reference or an explanation of the aliasing system, stating that OVN/OVS binaries can be executed either via `microovn.` prefixed commands or directly thanks to automatically created aliases (that can be inspected via `snap aliases`). Also, since these auto aliases are not related to the microovn snap version, but rather they are something managed by the snap store, it would be good to find out if (when?) existing installations gain access to these aliases, and document that as well. Otherwise just dropping the prefixes in the documentation can lead to a confusion of users of existing installations.

While I appreciate the quest for improving the documentation further, I wonder if we might be reaching into the responsibilities of generic snap documentation if we dive to deep into the alias topic. Would it perhaps be sufficient to mention that there are multiple ways to call binaries from the snap and link to https://snapcraft.io/docs/commands-and-aliases ?

On the topic of when the aliases come into effect, we have anecdotal evidence of them coming into effect on running systems without end user intervention, and from cursory view the `snapd` source code confirms this is the case:
https://github.com/canonical/snapd/blob/bd817d5d8c1d4732ad6a61346529dfe079ec963f/overlord/snapstate/snapstate.go#L2095

2024-12-03 10:34 UTC, mkalcok commented
> While I appreciate the quest for improving the documentation further, I wonder if we might be reaching into the responsibilities of generic snap documentation...

Perhaps a bit, but not too much imo. At least in the current state, auto-aliases are rather obscure. You won't find information about them neither on snapstore page, `snap info` nor in the code/`snapcraft.yaml`. So I think that the next best place is to document them in our docs.

> we have anecdotal evidence of them coming into effect on running systems without end user intervention

That is a good find, thank you. I think that this fact is well captured in this change with
```
These aliases are not related to the MicroOVN snap version and are managed by
the store. All installations should have access to these aliases.
```

2024-12-03 10:37 UTC, mkalcok commented on docs/reference/aliasing.rst
> +==================
Small note, as per Peter's comments, we should avoid using gerunds in the page titles.
https://github.com/canonical/microovn/pull/126#issuecomment-1984172113

2024-12-06 10:29 UTC, fnordahl commented
> > While I appreciate the quest for improving the documentation further, I wonder if we might be reaching into the responsibilities of generic snap documentation...
> 
> Perhaps a bit, but not too much imo. At least in the current state, auto-aliases are rather obscure. You won't find information about them neither on snapstore page, `snap info` nor in the code/`snapcraft.yaml`. So I think that the next best place is to document them in our docs.
> 
> > we have anecdotal evidence of them coming into effect on running systems without end user intervention
> 
> That is a good find, thank you. I think that this fact is well captured in this change with
> 
> ```
> These aliases are not related to the MicroOVN snap version and are managed by
> the store. All installations should have access to these aliases.
> ```

The page @crypticC0der added about auto aliases looks fine to me. Let's keep it!

You have a fair point about the lack of documentation on the snapd / snap store side. I'd suggest we raise an issue over there about it.

@crypticC0der on the topic of the flaky CI, would you have a moment to experiment with [Sphinx linkcheck options](https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-the-linkcheck-builder) to see if we can get it to behave? I know that you have not changed links as part of this change, but issues like this often creep up on software repositories, and fixing creeping issues unrelated to your change is a great way to motivate reviewers to accept your change!

2024-12-06 13:03 UTC, mkalcok commented
I have a one small note that I realized today as I was working with locally built microovn. Auto-aliases work only when installed via snapstore (understandable). We could add a small note about this to `developers/building.rst`

2024-12-12 09:47 UTC, mkalcok requested changes
Thanks for the update. I have one nit inline. otherwise LGTM.

2024-12-12 09:47 UTC, mkalcok commented on docs/conf.py
> +linkcheck_ignore = [r'.*cisa\.gov.*']
could we have a a short comment here explaining why we are skipping this check?

2024-12-12 09:58 UTC, mkalcok approved these changes
LGTM, thanks.

2024-12-12 09:59 UTC, merged

2024-12-12 15:59 UTC, crypticC0der commented
> The docs/conf.py file comes from [a template repository](https://github.com/canonical/sphinx-docs-starter-pack/blob/main/docs/conf.py). As a service to other travelers would you consider proposing a similar change there?

https://github.com/canonical/sphinx-docs-starter-pack/pull/317